# Generated by Django 3.2.24 on 2024-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
