# Generated by Django 3.2.24 on 2024-02-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_sku_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Sku',
            old_name='price',
            new_name='selling_price',
        ),
    ]
