# Generated by Django 3.2.24 on 2024-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240218_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
