# Generated by Django 3.2.24 on 2024-02-18 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240218_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='measurement_unit',
            field=models.CharField(choices=[('gm', 'gm'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pc', 'piece')], default='gm', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending for approval'), (1, 'Approved'), (2, 'Discontinued')], default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
